ARG IMAGE_NAME="engine.dev.ubuntu.18.04"
FROM $IMAGE_NAME

# From Zonemaster Backend installation instruction 
RUN apt-get install --no-install-recommends -qq libclass-method-modifiers-perl libconfig-inifiles-perl libdbd-sqlite3-perl libdbi-perl libfile-sharedir-perl libfile-slurp-perl libhtml-parser-perl libio-captureoutput-perl libjson-pp-perl libjson-rpc-perl liblog-any-adapter-dispatch-perl liblog-any-perl liblog-dispatch-perl libplack-perl libplack-middleware-debug-perl librole-tiny-perl librouter-simple-perl libstring-shellquote-perl starman

RUN cpan install Socket6

    # Install Zonemaster Engine
RUN git clone --depth=1 --branch=develop https://github.com/zonemaster/zonemaster-engine.git && \
    ( cd zonemaster-engine && cpanm --verbose --notest . ) && rm -rf zonemaster-engine

ARG DB 
ARG ZONEMASTER_BACKEND_CONFIG_FILE
ENV ZONEMASTER_BACKEND_CONFIG_FILE $ZONEMASTER_BACKEND_CONFIG_FILE

COPY . /zonemaster-backend
WORKDIR zonemaster-backend

RUN if [ "$DB" = "postgres" ]; then \
    apt-get install -qq --no-install-recommends libpq-dev libdbd-pg-perl postgresql-client postgresql && \
    cpanm DBD::Pg && cpanm --installdeps . && \
    sed -i 's/peer/trust/' /etc/postgresql/*/main/pg_hba.conf && \
    service postgresql start && \
    psql -c "create user travis_zonemaster WITH PASSWORD 'travis_zonemaster';"  -U postgres && \
    psql -c 'create database travis_zonemaster OWNER travis_zonemaster;' -U postgres && \
    perl -I./lib ./script/create_db_postgresql_9.3.pl && \
    sed -i 's/peer/md5/' /etc/postgresql/*/main/pg_hba.conf; \
    fi