ARG IMAGE_NAME="ubuntu:latest"
FROM $IMAGE_NAME

ARG PERL_VERSION
ARG DB
ARG DB_VERSION

# Install a couple dependencies + extra packages
RUN apt-get update --fix-missing && apt-get install -y -q \
    apt-utils \
    build-essential \
    curl \
    gcc \
    git \
    gpp \
    libncurses5-dev \
    libreadline-dev \
    libssl-dev &>/dev/null

# Installation of the right PERL version
RUN curl -L https://install.perlbrew.pl | bash && \
echo " perl-$PERL_VERSION " && \
~/perl5/perlbrew/bin/perlbrew install perl-$PERL_VERSION && ~/perl5/perlbrew/bin/perlbrew switch perl-$PERL_VERSION

RUN echo $PERL_VERSION

# From Zonemaster Engine installation instruction 
RUN apt-get install -y --no-install-recommends autoconf automake build-essential cpanminus libclone-perl libfile-sharedir-perl libfile-slurp-perl libidn11-dev libintl-perl libio-socket-inet6-perl libjson-pp-perl liblist-moreutils-perl liblocale-msgfmt-perl libmail-rfc822-address-perl libmodule-find-perl libnet-ip-perl libpod-coverage-perl libreadonly-perl libreadonly-xs-perl libssl-dev libtest-differences-perl libtest-exception-perl libtest-fatal-perl libtest-pod-perl libtext-csv-perl libtool m4

# From Zonemaster Backend installation instruction 
RUN apt-get install -y --no-install-recommends libclass-method-modifiers-perl libconfig-inifiles-perl libdbd-sqlite3-perl libdbi-perl libfile-sharedir-perl libfile-slurp-perl libhtml-parser-perl libio-captureoutput-perl libjson-pp-perl libjson-rpc-perl liblog-any-adapter-dispatch-perl liblog-any-perl liblog-dispatch-perl libplack-perl libplack-middleware-debug-perl librole-tiny-perl librouter-simple-perl libstring-shellquote-perl starman

# Zonemaster LDNS needs a newer version of Module::Install
RUN cpan-install Module::Install Module::Install::XSUtil && \
    # Zonemaster Backend transitively needs a newer version of Devel::CheckLib
    cpan-install Devel::CheckLib && \
    # Moose installed from OS packages depend on a newer version of Devel::OverloadInfo
    cpan-install Devel::OverloadInfo Moose && \ 
    # IO::Socket::INET6 can't find Socket6 unless it's installed from CPAN
    cpan-install Socket6


    # Install Zonemaster LDNS
RUN git clone --depth=1 --branch=develop https://github.com/zonemaster/zonemaster-ldns.git && \
    ( cd zonemaster-ldns && cpanm --verbose --notest --configure-args="--no-ed25519" . ) && rm -rf zonemaster-ldns

    # Install Zonemaster Engine
RUN git clone --depth=1 --branch=develop https://github.com/zonemaster/zonemaster-engine.git && \
    ( cd zonemaster-engine && cpanm --verbose --notest . ) && rm -rf zonemaster-engine

RUN if [ "$DB" = "postgres" ]; then \
    apt-get install -y --no-install-recommends python-software-properties software-properties-common postgresql-$DB_VERSION postgresql-client-$DB_VERSION postgresql-contrib-$DB_VERSION && \
    psql -c "create user travis_zonemaster WITH PASSWORD 'travis_zonemaster';" -U postgres && \
    psql -c 'create database travis_zonemaster OWNER travis_zonemaster;' -U postgres && \
    cpanm DBD::Pg && \
    perl -I./lib ./script/create_db_postgresql_$DB_VERSION.pl; fi 

CMD ["/usr/lib/postgresql/$DB_VERSION/bin/postgres", "-D", "/var/lib/postgresql/$DB_VERSION/main", "-c", "config_file=/etc/postgresql/$DB_VERSION/main/postgresql.conf"]